apiVersion: 'v1'
kind: 'ConfigMap'
metadata:
  name: 'coredns-custom'
  namespace: 'kube-system'
data:
  metadata.server: |
    metadata.google.internal:53 {
      errors
      hosts {
        169.254.169.254 metadata.google.internal
      }
    }
