apiVersion: 'rbac.authorization.k8s.io/v1'
kind: 'ClusterRoleBinding'
metadata:
  name: 'metadata-server'
subjects:
  - kind: 'ServiceAccount'
    name: 'metadata-server'
    namespace: '{{ $.Release.Namespace }}'
roleRef:
  kind: 'ClusterRole'
  name: 'metadata-server'
  apiGroup: ''
