apiVersion: 'rbac.authorization.k8s.io/v1'
kind: 'ClusterRole'
metadata:
  name: 'metadata-server'
rules:
- apiGroups: ['']
  verbs: ['get', 'list']
  resources:
  - 'pods'
- apiGroups: ['']
  verbs: ['get']
  resources:
  - 'serviceaccounts'
  - 'nodes/proxy'
- apiGroups: ['']
  verbs: ['create']
  resources:
  - 'serviceaccounts/token'
- apiGroups: ['authentication.k8s.io']
  verbs: ['get', 'list', 'create', 'update', 'delete']
  resources:
  - 'tokenrequests'
