name: 'Pull Request Labeler'
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  path_labeler:
    runs-on: ['ubuntu-24.04']
    permissions:
      contents: 'read'
      pull-requests: 'write'

    steps:
      - name: 'assign path based labels'
        uses: 'actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9' # ratchet:actions/labeler@v5

  commit_labeler:
    runs-on: ['ubuntu-24.04']
    permissions:
      contents: 'read'
      pull-requests: 'write'

    steps:
      - name: 'assign commit based labels'
        uses: mauroalderete/action-assign-labels@671a4ca2da0f900464c58b8b5540a1e07133e915 # ratchet:mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          maintain-labels-not-matched: true
          apply-changes: true
          conventional-commits: |
            conventional-commits:
              - type: 'bug'
                nouns: ['FIX', 'Fix', 'fix']
                labels: ['ğŸ bug']
              - type: 'feature'
                nouns: ['FEAT', 'Feat', 'feat']
                labels: ['â­ï¸ feature']
              - type: 'chore'
                nouns: ['CHORE', 'Chore', 'chore']
                labels: ['ğŸ§¹ chore']
              - type: 'refactor'
                nouns: ['REFACTOR', 'Refactor', 'refactor']
                labels: ['ğŸ› ï¸ refactoring']
              - type: 'security'
                nouns: ['SECURITY', 'Security', 'security']
                labels: ['ğŸ”“ security']
