name: 'release-please'
on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/release-please-config.json'
      - '.github/release-please-manifest.json'
      - '.github/workflows/release-please.yaml'
      - 'justfile'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ['ubuntu-24.04']
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: write

    steps:
      - uses: 'googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c' # ratchet:googleapis/release-please-action@v4
        id: release
        with:
          config-file: '.github/release-please-config.json'
          manifest-file: '.github/release-please-manifest.json'

      - name: 'Debug release-please outputs'
        id: debug
        env:
          RELEASE_PLEASE_OUTPUTS: ${{ toJson(steps.release.outputs) }}
        run: |
          echo "Release-please outputs: $RELEASE_PLEASE_OUTPUTS"

    outputs:
      full: ${{ toJson(steps.release.outputs) }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      releases_created: ${{ steps.release.outputs.releases_created }}

  debug-release-please-outputs:
    needs: 'release-please'
    if: always()
    runs-on: ['ubuntu-24.04']
    steps:
      - name: 'Debug release-please outputs'
        env:
          NEEDS: ${{ toJson(needs) }}
        run: |
          echo "Needs: $NEEDS"

  deploy-please:
    needs: 'release-please'
    if: needs.release-please.outputs.releases_created == 'true'
    strategy:
      matrix:
        path: ${{ fromJson(needs.release-please.outputs.paths_released) }}

    runs-on: ['ubuntu-24.04']
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5
        with:
          ref: ${{ fromJson(needs.release-please.outputs.full)[format('{0}--tag_name', matrix.path)] }}

      - name: 'Setup golang'
        uses: 'actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00' # ratchet:actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: 'Setup just'
        uses: 'extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff' # ratchet:extractions/setup-just@v3

      - name: Log in to the Container registry
        uses: 'docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef' # ratchet:docker/login-action@v3
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: 'docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392' # ratchet:docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: 'docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435' # ratchet:docker/setup-buildx-action@v3

      - name: 'Build and publish ${{ matrix.path }}'
        env:
          CMD: ${{ matrix.path }}
        run: |
          CMD="${CMD#*/}"
          just build-multiarch "$CMD" $(just version "$CMD") --push
