name: 'test container image builds'

'on':
  workflow_dispatch: {}
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened]
    paths:
      - 'docker/**'
      - '.dockerignore'
      - 'justfile'
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
  push:
    paths:
      - 'docker/**'
      - '.dockerignore'
      - 'justfile'
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    if: github.event_name != 'issue_comment' || startsWith(github.event.comment.body, '/build')
    runs-on: ['ubuntu-24.04']
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    strategy:
      matrix:
        target:
          - identity-server
          - metadata-iptables-init
          - metadata-server
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5

      - name: 'Setup golang'
        uses: 'actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00' # ratchet:actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: 'Setup just'
        uses: 'extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff' # ratchet:extractions/setup-just@v3

      - name: Log in to the Container registry
        uses: 'docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef' # ratchet:docker/login-action@v3
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: 'docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435' # ratchet:docker/setup-buildx-action@v3

      - name: 'Build ${{ matrix.target }}'
        run: |
          just build-multiarch "${{ matrix.target }}" \
            "$(just version "${{ matrix.target }}")-test-${{ github.run_number }}" \
            --push
